<?php
$clickheatConf = array (
  'logPath' => ROOT_DIR.'/html/files/clickheat/logs/',
  'cachePath' => ROOT_DIR.'/html/files/clickheat/cache/',
  'referers' => false,
  'groups' => false,
  'filesize' => 0,
  'adminLogin' => 'kenta@diverta.co.jp',
  'adminPass' => '098f6bcd4621d373cade4e832627b4f6',
  'viewerLogin' => '',
  'viewerPass' => '',
  'memory' => 100,
  'step' => 5,
  'dot' => 19,
  'flush' => 40,
  'start' => 'm',
  'palette' => false,
  'heatmap' => true,
  'hideIframes' => true,
  'hideFlashes' => true,
  'yesterday' => false,
  'alpha' => 80,
  'version' => '1.8-revC',
);
